using MasterDevs.ChromeDevTools;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace MasterDevs.ChromeDevTools.Protocol.CSS
{
	/// <summary>
	/// CSS style information for a DOM style attribute.
	/// </summary>
	[SupportedBy("iOS-9.3")]
	public class CSSStyleAttribute
	{
		/// <summary>
		/// Gets or sets DOM attribute name (e.g. "width").
		/// </summary>
		[SupportedBy("iOS-9.3")]
		public string Name { get; set; }
		/// <summary>
		/// Gets or sets CSS style generated by the respective DOM attribute.
		/// </summary>
		[SupportedBy("iOS-9.3")]
		public CSSStyle Style { get; set; }
	}
}
